name: "pysolarmanv5-proxy"
description: "Addon to control deye inverters"
version: "1.0.1"
slug: "pysolarmanv5-proxy"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_role: default
homeassistant_api: true
hassio_api: true

schema:
  ip: "str?"
  serialnumber: "str?"
