name: "deye-solarmanpy"
description: "Addon to control deye inverters"
version: "1.0.8"
slug: "deye-solarmanpy"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_role: default
homeassistant_api: true
hassio_api: true
schema:
  ip: "str?"
  serialnumber: "str?"
  max_bat_charge_amps: "int?40"
  min_bat_soc: "int(20)?"
  max_bat_soc: "int(90)?"
