name: "deye-solarmanpy"
description: "Addon to control deye inverters"
version: "1.0.10"
slug: "deye-solarmanpy"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_role: default
homeassistant_api: true
hassio_api: true
options:
  max_bat_charge_amps: "40" # max charge amps to inverter
  min_bat_soc: "20"
  max_bat_soc: "90"
schema:
  ip: "str?"
  serialnumber: "str?"
  max_bat_charge_amps: "float(1,200)?"
  min_bat_soc: "float(1,100)?"
  max_bat_soc: "float(1,100)?"
