name: "deye-solarmanpy"
description: "Addon to control deye inverters"
version: "1.0.0"
slug: "deye-solarmanpy"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_role: default
homeassistant_api: true
hassio_api: true
options:
  ip: 192.168.1.100
  serialnumber: 000000
